### ISSUE TITLE
Please add a favicon

### ISSUE THREAD

**Issue by cbrock** [humanchimp/php#1]
I use this site quite a bit so end up leaving the tab open in my browser for long periods of time.

It would be nice to differentiate this tab from others with a favicon that matched the taste and elegance of the site itself.

**Comment by krothenbaum** [comment]
@cbrock favicons are for people who can't memorize their open tabs and their order. I think the web was better without them and this site should not add one imo.

don't @ me.

**Comment by humanchimp** [comment]
This flame war is getting out of hand

**Comment by humanchimp** [comment]
closed via 14c02998e836ac0efbf4ac3a5d16f8868cd184ee
